# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to GitHub Pages

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        npm install -g yarn
        npm install
        yarn install
      
    - name: Build yarn
      env:
        CI: false
      run: |
        yarn run build
        
    - name: Deploy
      uses: PublicHealthEngland/coronavirus-dashboard@development
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages-dev # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        package: ./build
        app-name: 'covid19dashboardtest'
